/* CONFIGURATION VARIABLES */
typedef unsigned char byte;
enum status {SUCCESS=0, ERR_HMAC_UPDATE, ERR_COMPRESSION, ERR_ENCRYPTION, ERR_HMAC_FINALIZATION, ERR_CORRUPTED_FILE, ERR_INCOMPATIBLE_VERSION};
const byte LINETYPES_UNCOMPRESSED = 0, LINETYPES_SHOCO = 1, LINETYPES_DEFLATE = 2, LINETYPES_ERROR = 255;
const uint32_t VERSION = 5;
const size_t MASTER_KEY_LEN = 32;